name: spindleshare
description: SpindleShare app scaffold (complete)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.2.0
  cloud_functions: ^4.1.0
  firebase_messaging: ^14.3.0
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  cached_network_image: ^3.2.4
  intl: ^0.18.0
  file_picker: ^5.2.5
  uuid: ^3.0.7
  http: ^0.13.6
  url_launcher: ^6.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
