name: Flutter Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK per ABI
        env:
          JAVA_TOOL_OPTIONS: "-Xmx4g"
          GRADLE_OPTS: "-Xmx4g"
        run: flutter build apk --release --split-per-abi --no-shrink

      - name: Upload All APKs
        uses: actions/upload-artifact@v4
        with:
          name: all-apk
          path: build/app/outputs/flutter-apk/*.apk
