name: Flutter Android Build (Safe)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (arm64 only)
        env:
          JAVA_TOOL_OPTIONS: "-Xmx4g"
          GRADLE_OPTS: "-Xmx4g"
        run: flutter build apk --release --target-platform android-arm64 --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-arm64
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
